routes/auth.py
from flask import Blueprint
from flask import render_template
from flask import request
from flask import redirect
from flask import url_for
from flask import flash
from flask import current_app   # definisce il contesto del modulo
from flask_login import login_user  # https://flask-login.readthedocs.io/en/latest/#flask_login.login_user
from flask_login import logout_user
from flask_login import login_required, current_user

from models.connection import db
from models.model import *

auth = Blueprint('auth', __name__)

@auth.route('/login')
def login():
    # shows the login form page
    return render_template('auth/login.html')

@auth.route("/signup")
def signup():
    return render_template('auth/signup.html')

@auth.route('/signup', methods=['POST'])
def signup_post():
    # signup input validation and logic
    #TODO verify password strenght
    username = request.form["username"] #as an alternative use request.form.get("username")
    email = request.form["email"]    
    password = request.form["password"]

    if not username:
        flash('Invalid username')
        return redirect(url_for('auth.signup'))
    if not email:
        flash('Invalid email')
        return redirect(url_for('auth.signup'))
    if not password:
        flash('Invalid password')
        return redirect(url_for('auth.signup'))                
    
    user = User.query.filter_by(email=email).first() # if this returns a user, then the email already exists in database
    if user: 
        # if a user is found, we want to redirect back to signup page so user can try again
        # display some kind of error
        flash('User with this email address already exists')
        return redirect(url_for('auth.signup'))

    user = User(username=username, email=email)
    user.set_password(password)  # Imposta la password criptata
    db.session.add(user)  # equivalente a INSERT
    db.session.commit()

    return redirect(url_for('auth.login'))

@auth.route('/login', methods=['POST'])
def login_post():
    # manages the login form post request
    email = request.form.get('email')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False

    user = User.query.filter_by(email=email).first()

    # check if the user actually exists
    # take the user-supplied password, hash it, and compare it to the hashed password in the database
    if not user or not user.check_password(password):
        flash('Please check your login details and try again.')
        return redirect(url_for('auth.login')) # if the user doesn't exist or password is wrong, reload the page

    # if the above check passes, then we know the user has the right credentials
    login_user(user, remember=remember)
    return redirect(url_for('auth.profile'))    

@auth.route('/profile')
@login_required
def profile():
    return render_template('auth/profile.html', name=current_user.username)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return 'Logout'

routes/image.py
from flask import Blueprint, render_template, request,redirect,url_for
import torch
from diffusers import StableDiffusionPipeline
from datetime import datetime
import uuid
from models.connection import db
from models.model import *
from flask_login import login_required, current_user
import time
from PIL.PngImagePlugin import PngInfo
import os

# Replace the model version with your required version if needed
pipeline = StableDiffusionPipeline.from_pretrained(
    "stabilityai/stable-diffusion-2", torch_dtype=torch.float16
)

# Running the inference on GPU with cuda enabled
pipeline = pipeline.to('cuda')
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "max_split_size_mb:32"
# Get device
img = Blueprint("img", __name__)

@img.route("/image-generation/<id>", methods=["GET"])
def get_image(id):
    res = Resource.query.filter_by(resourceID=id).first()
    if res.audio == 0:
        user = User.query.filter_by(id=res.userID).first()
        return render_template("show-image.html",image=id, prompt=res.prompt,user=user.username)
    else:
        return redirect("/text-to-speech/"+res.resourceID)

@img.route("/image-generation", methods=["GET"])
def form():
    if current_user.is_authenticated:
        return render_template("insert-generation.html")
    else:
        return redirect(url_for('auth.login', next=request.url))

@img.route("/image-generation", methods=["POST"])
def create():
    if current_user.is_authenticated:
        txt = request.form.get("text")
        torch.cuda.empty_cache() 
        image = pipeline(prompt=txt, ).images[0]
        metadata = PngInfo()
        metadata.add_text("prompt",txt)
        id =uuid.uuid4()
        filepath= f"static/generated-images/{id}"
        while os.path.isfile(filepath):
            id=uuid.uuid5()
            filepath= f"static/generated-images/{id}"
        image.save(filepath, "PNG", pnginfo=metadata)
        
        res = Resource(resourceID=str(id), userID=1,prompt=txt,audio=False,date=time.time_ns())
        db.session.add(res)
        db.session.commit()
        return {"resourceID": str(id)}
    else:
        return redirect(url_for('auth.login', next=request.url))

routes/speech.py
from flask import Blueprint, render_template, request,redirect,url_for
import pyttsx3
import time
from flask_login import login_required, current_user
from models.model import *
import uuid
import os
# conn = sqlite3.connect('TTS.db', check_same_thread=False)
# Get device
speech = Blueprint("speech", __name__)

@speech.route("/text-to-speech", methods=["GET"])
def form():
    if current_user.is_authenticated:
        return render_template("insert.html")
    else:
        return redirect(url_for('auth.login', next=request.url))

@speech.route("/text-to-speech/<id>", methods=["GET"])
def get(id):
    res = Resource.query.filter_by(resourceID=id).first()
    if res.audio == 1:
        user = User.query.filter_by(id=res.userID).first()
        return render_template("download.html",image=id, prompt=res.prompt,user=user.username)
    else:
        return redirect("/image-generation/"+res.resourceID)

@speech.route("/text-to-speech", methods=["POST"])
def convert():
    if current_user.is_authenticated:
        txt = request.form.get("text")
        # wav = tts.tts(text=txt, speaker_wav="static/audio/audio.wav", language="en")
        # tts.tts_to_file(text="Hello world!", speaker_wav="static/audio/audio.wav", language="en", file_path="static/audio/output.wav")
        engine = pyttsx3.init()
        engine.setProperty('rate', 150)  # Speed of speech (words per minute)
        engine.setProperty('volume', 1.0)
        id = uuid.uuid4()
        filepath= f"static/audio/{id}.mp3"
        while os.path.isfile(filepath):
            id=uuid.uuid5()
            filepath= f"static/audio/{id}.mp3"
        engine.save_to_file(txt, filepath)
        engine.runAndWait()
        res = Resource(resourceID=str(id),userID=current_user.id,prompt=txt,audio=True,date=time.time_ns())
        db.session.add(res)
        db.session.commit()
        return {"resourceID": str(id)}
    else:
        return redirect(url_for('auth.login', next=request.url))

templates/base.html
<!DOCTYPE html>
<!-- base.html -->
<html>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='/images/icon.ico') }}">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#"><img src="{{url_for('static', filename='/images/icon.ico')}}" width="100"></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="/">Home</a>
              </li>
              <li class="nav-item"><a class="nav-link" href="{{ url_for('speech.form')}}">TTS</a></li>
              <li class="nav-item"><a class="nav-link" href="{{ url_for('img.form')}}">TTI</a></li>
              {% if not current_user.is_authenticated %}
              <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.login') }}">Login</a></li>
              <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.signup') }}">Sign up</a></li>
              {% endif %}
              {% if current_user.is_authenticated %}
              <li class="nav-item"><a class="nav-link" href="{{ url_for('my_prompts') }}">My Prompts</a></li>
              <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.profile') }}">Profile</a></li>
              <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a></li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>

    <div class="container">
        <!-- Content here -->
        {% block content %}{% endblock %}     
    </div>
</body>
</html>

templates/download.html
{% extends "base.html" %}

{% block title %}Flask Login{% endblock %}

{% block content %}
  <h2>Ascolta o Scarica il File WAV</h2>
  <audio controls>
    <source src="/static/audio/{{path}}" type="audio/wav">
    Il tuo browser non supporta l'elemento audio.
  </audio>
  <h2>User: {{ user }}</h2>
  <h2>prompt: {{prompt}}</h2>
  <br>
  <a href="{{path}}" download>Scarica il File WAV</a>
{% endblock%}

templates/image-viewer.html
{% extends "base.html" %}

{% block title %}Flask Login{% endblock %}

{% block content %}
  <h2>Visualizza</h2>
    <img src="{{path}}">
  <br>
  <a href="{{path}}" download>Scarica la tua immagine</a>
{% endblock%}

templates/index.html
{% extends "base.html" %}

{% block title %}GG{% endblock %}

{% block content %}
        Recently created audios
        <div  style="overflow-y:auto;">
            <table>
                {% for audio in audios%}
                    <audio controls class="w-100" src="static/audio/{{audio.resourceID}}.mp3"></audio>
                {% endfor %}
            </table>
        </div>
        Recently created images
        <div  style="overflow-y:auto;">
            <table>
                {% for image in images %}
                    <div>
                        <a href="/image-generation/{{image.resourceID}}"><img class="img-thumbnail" src="/static/generated-images/{{image.resourceID}}"></a>
                    </div>
                {% endfor %}
            </table>
        </div>
{% endblock%}

templates/insert-generation.html
{% extends "base.html" %}

{% block title %}Flask Login{% endblock %}

{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<style>

  .center {
    margin: 0 auto;
    display: none;
  }
  
  .outer-ring {
    position: absolute;
    top: calc(50% - 50px);
    left: calc(50% - 50px);
    height: 100px;
    width: 100px;
    background-image: linear-gradient(135deg, #FEED07 0%, #FE6A50 5%, #ED00AA 15%, #2FE3FE 50%, #8900FF 100%);
    border-radius: 50%;
    
    /*  Rotate  */
    animation-duration: 3s;
    animation-name: rotate;
    animation-iteration-count: infinite;
    animation-timing-function: linear;
  }
  
  .inner-ring {
    position: absolute;
    top: calc(50% - 45px);
    left: calc(50% - 45px);
    height: 90px;
    width: 90px;
    background-color: rgb(40, 40, 40);
    border-radius: 50%;
  }
  
  @keyframes rotate {
      0% {transform:rotate(0deg);}
      100% {transform:rotate(360deg);}
  }
    </style>

  <form>
    <label for="testo">Inserisci il tuo testo per creare l'immagine:</label>
    <input type="text" id="testo" name="text">
    <input type="submit" value="Invia" id="submit" >
  </form>
  <div class="outer-ring center" id="outer"></div>
  <div class="inner-ring center" id="inner"></div>  
  <script>
    document.getElementById("submit").addEventListener("click", function(event) {
      event.preventDefault();
      console.log("Showing loading screen");
      document.getElementById("outer").style.display = "block";
      document.getElementById("inner").style.display = "block";
      var txt = document.getElementById("testo").value;
      console.log(txt);
      $.post("/image-generation",
        {
          text: txt
        }
      ,function(data,status){
        if(status=="success") {
          console.log(data)
          window.location = "/image-generation/"+data.resourceID;
        } else{
          alert(status)
        }
    }); 
    });
  </script>
{% endblock%}

templates/insert.html
{% extends "base.html" %}

{% block title %}Flask Login{% endblock %}

{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<style>

  .center {
    margin: 0 auto;
    display: none;
  }
  
  .outer-ring {
    position: absolute;
    top: calc(50% - 50px);
    left: calc(50% - 50px);
    height: 100px;
    width: 100px;
    background-image: linear-gradient(135deg, #FEED07 0%, #FE6A50 5%, #ED00AA 15%, #2FE3FE 50%, #8900FF 100%);
    border-radius: 50%;
    
    /*  Rotate  */
    animation-duration: 3s;
    animation-name: rotate;
    animation-iteration-count: infinite;
    animation-timing-function: linear;
  }
  
  .inner-ring {
    position: absolute;
    top: calc(50% - 45px);
    left: calc(50% - 45px);
    height: 90px;
    width: 90px;
    background-color: rgb(40, 40, 40);
    border-radius: 50%;
  }
  
  @keyframes rotate {
      0% {transform:rotate(0deg);}
      100% {transform:rotate(360deg);}
  }
    </style>
  <form>
    <label for="testo">Inserisci il tuo testo:</label>
    <input type="text" id="testo" name="text">
    <input type="submit" value="Invia" id="submit" >
  </form>
  <div class="outer-ring center" id="outer"></div>
  <div class="inner-ring center" id="inner"></div>  
  <script>
    document.getElementById("submit").addEventListener("click", function(event) {
      event.preventDefault();
      console.log("Showing loading screen");
      document.getElementById("outer").style.display = "block";
      document.getElementById("inner").style.display = "block";
      var txt = document.getElementById("testo").value;
      console.log(txt);
      $.post("/text-to-speech",
        {
          text: txt
        }
      ,function(data,status){
        if(status=="success") {
          console.log(data)
          window.location = "/text-to-speech/"+data.resourceID;
        } else{
          alert(status)
        }
    }); 
    });
  </script>
{% endblock%}

templates/prompts.html
{% extends "base.html" %}

{% block title %}GG{% endblock %}

{% block content %}
        Recently created audios
        <div  style="overflow-y:auto;">
            <table>
                {% for audio in audios %}
                    <audio controls class="w-100" src="static/audio/{{audio.resourceID}}.mp3"></audio>
                {% endfor %}
            </table>
        </div>
        Recently created images
        <div  style="overflow-y:auto;" id="image-table">
            <table>
                {% for image in images %}
                    <div>
                        <a href="/image-generation/{{image.resourceID}}"><img class="img-thumbnail" src="/static/generated-images/{{image.resourceID}}"></a>
                    </div>
                {% endfor %}
            </table>
        </div>
        <button onclick="loadmore">
{% endblock%}

templates/show-image.html
{% extends "base.html" %}

{% block title %}Flask Login{% endblock %}
{% block content %}
    <img class="img-thumbnail" src="/static/generated-images/{{image}}">
    <h2>user: {{user}}</h2>
    <h3>prompt: {{prompt}}</h3>
{% endblock %}